// Generated by ugts_kc3.androidexport; do not edit.
#pragma once
#include <array>
#include <cstdint>
#include <string_view>

namespace kc::chrono_runtime_binding {

struct AssetBinding {
    std::string_view path;
    std::uint64_t bytes;
    std::array<std::uint8_t, 32> sha256;
};

inline constexpr bool kPresent = false;
inline constexpr std::string_view kManifestAssetPath{""};
inline constexpr std::string_view kManifestSha256Hex{""};
inline constexpr std::array<std::uint8_t, 32> kManifestSha256{{0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u}};
inline constexpr std::string_view kProfileAssetPath{""};
inline constexpr std::string_view kProfileSha256Hex{""};
inline constexpr std::array<std::uint8_t, 32> kProfileSha256{{0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u}};
inline constexpr std::array<AssetBinding, 0> kAssets{};

[[nodiscard]] inline constexpr const AssetBinding* find(
    std::string_view path) noexcept {
    for (const auto& asset : kAssets) {
        if (asset.path == path) return &asset;
    }
    return nullptr;
}

} // namespace kc::chrono_runtime_binding
