#include "camera_ndk.hpp"
#include "android_log.hpp"
#include <camera/NdkCameraMetadata.h>
#include <media/NdkImage.h>
#include <algorithm>
#include <cmath>
#include <cstring>
#include <limits>
#include <sstream>
namespace ugts41::android {
namespace {bool ok(camera_status_t s,const char*where){if(s==ACAMERA_OK)return true;UGTS_LOGE("%s camera status=%d",where,int(s));return false;}bool mok(media_status_t s,const char*where){if(s==AMEDIA_OK)return true;UGTS_LOGE("%s media status=%d",where,int(s));return false;}}
bool CameraNdk::choose_camera(std::uint16_t rw,std::uint16_t rh,std::uint16_t fps){ACameraIdList*list=nullptr;if(!ok(ACameraManager_getCameraIdList(manager_,&list),"get id list")||!list)return false;long best_score=std::numeric_limits<long>::max();std::string best;std::uint16_t bw=0,bh=0;std::string facing="unknown";std::ostringstream calibration;for(int i=0;i<list->numCameras;i++){const char*id=list->cameraIds[i];ACameraMetadata*meta=nullptr;if(!ok(ACameraManager_getCameraCharacteristics(manager_,id,&meta),"characteristics")||!meta)continue;ACameraMetadata_const_entry lens{};std::uint8_t face=255;if(ACameraMetadata_getConstEntry(meta,ACAMERA_LENS_FACING,&lens)==ACAMERA_OK&&lens.count)face=lens.data.u8[0];if(face!=ACAMERA_LENS_FACING_BACK){ACameraMetadata_free(meta);continue;}ACameraMetadata_const_entry streams{};if(ACameraMetadata_getConstEntry(meta,ACAMERA_SCALER_AVAILABLE_STREAM_CONFIGURATIONS,&streams)==ACAMERA_OK){for(std::uint32_t j=0;j+3<streams.count;j+=4){int format=streams.data.i32[j],w=streams.data.i32[j+1],h=streams.data.i32[j+2],input=streams.data.i32[j+3];if(input||format!=AIMAGE_FORMAT_YUV_420_888||w<=0||h<=0)continue;long score=std::labs(w-int(rw))*2L+std::labs(h-int(rh))*2L+std::labs((w*9)-(h*16))/100L;if(score<best_score){best_score=score;best=id;bw=w;bh=h;facing="back";}}}ACameraMetadata_const_entry focal{},sensor{};if(ACameraMetadata_getConstEntry(meta,ACAMERA_LENS_INFO_AVAILABLE_FOCAL_LENGTHS,&focal)==ACAMERA_OK&&focal.count)calibration<<"focal_mm="<<focal.data.f[0]<<';';if(ACameraMetadata_getConstEntry(meta,ACAMERA_SENSOR_INFO_PHYSICAL_SIZE,&sensor)==ACAMERA_OK&&sensor.count>=2)calibration<<"sensor_mm="<<sensor.data.f[0]<<'x'<<sensor.data.f[1]<<';';ACameraMetadata_free(meta);}
ACameraManager_deleteCameraIdList(list);if(best.empty())return false;camera_id_=best;descriptor_.camera_id=best;descriptor_.facing=facing;descriptor_.width=bw;descriptor_.height=bh;descriptor_.fps=fps;calibration<<"stream="<<bw<<'x'<<bh<<";fps="<<fps;descriptor_.calibration=calibration.str();return true;}
bool CameraNdk::start(std::uint16_t w,std::uint16_t h,std::uint16_t fps){stop();manager_=ACameraManager_create();if(!manager_||!choose_camera(w,h,fps)){UGTS_LOGE("no usable back YUV camera");stop();return false;}if(!mok(AImageReader_new(descriptor_.width,descriptor_.height,AIMAGE_FORMAT_YUV_420_888,4,&reader_),"image reader")){stop();return false;}AImageReader_ImageListener listener{this,on_image};if(!mok(AImageReader_setImageListener(reader_,&listener),"image listener")||!mok(AImageReader_getWindow(reader_,&reader_window_),"reader window")){stop();return false;}ANativeWindow_acquire(reader_window_);ACameraDevice_StateCallbacks dcb{this,on_disconnected,on_error};if(!ok(ACameraManager_openCamera(manager_,camera_id_.c_str(),&dcb,&device_),"open camera")){stop();return false;}if(!ok(ACameraDevice_createCaptureRequest(device_,TEMPLATE_PREVIEW,&request_),"create request")){stop();return false;}std::int32_t range[2]={fps,fps};ACaptureRequest_setEntry_i32(request_,ACAMERA_CONTROL_AE_TARGET_FPS_RANGE,2,range);std::uint8_t af=ACAMERA_CONTROL_AF_MODE_CONTINUOUS_VIDEO;ACaptureRequest_setEntry_u8(request_,ACAMERA_CONTROL_AF_MODE,1,&af);if(!ok(ACameraOutputTarget_create(reader_window_,&target_),"target")||!ok(ACaptureRequest_addTarget(request_,target_),"request target")||!ok(ACaptureSessionOutputContainer_create(&outputs_),"output container")||!ok(ACaptureSessionOutput_create(reader_window_,&output_),"session output")||!ok(ACaptureSessionOutputContainer_add(outputs_,output_),"add output")){stop();return false;}ACameraCaptureSession_stateCallbacks scb{this,on_closed,on_ready,on_active};if(!ok(ACameraDevice_createCaptureSession(device_,outputs_,&scb,&session_),"capture session")){stop();return false;}if(!ok(ACameraCaptureSession_setRepeatingRequest(session_,nullptr,1,&request_,nullptr),"repeating request")){stop();return false;}UGTS_LOGI("camera=%s stream=%ux%u@%u",camera_id_.c_str(),descriptor_.width,descriptor_.height,descriptor_.fps);return true;}
void CameraNdk::stop(){if(session_){ACameraCaptureSession_stopRepeating(session_);ACameraCaptureSession_abortCaptures(session_);ACameraCaptureSession_close(session_);session_=nullptr;}if(request_){if(target_)ACaptureRequest_removeTarget(request_,target_);ACaptureRequest_free(request_);request_=nullptr;}if(target_){ACameraOutputTarget_free(target_);target_=nullptr;}if(outputs_&&output_)ACaptureSessionOutputContainer_remove(outputs_,output_);if(output_){ACaptureSessionOutput_free(output_);output_=nullptr;}if(outputs_){ACaptureSessionOutputContainer_free(outputs_);outputs_=nullptr;}if(device_){ACameraDevice_close(device_);device_=nullptr;}if(reader_){AImageReader_delete(reader_);reader_=nullptr;}if(reader_window_){ANativeWindow_release(reader_window_);reader_window_=nullptr;}if(manager_){ACameraManager_delete(manager_);manager_=nullptr;}camera_id_.clear();}
void CameraNdk::on_image(void*ctx,AImageReader*r){static_cast<CameraNdk*>(ctx)->acquire_image(r);}void CameraNdk::on_disconnected(void*,ACameraDevice*){UGTS_LOGW("camera disconnected");}void CameraNdk::on_error(void*,ACameraDevice*,int e){UGTS_LOGE("camera error=%d",e);}void CameraNdk::on_closed(void*,ACameraCaptureSession*){}void CameraNdk::on_ready(void*,ACameraCaptureSession*){}void CameraNdk::on_active(void*,ACameraCaptureSession*){}
void CameraNdk::acquire_image(AImageReader*r){AImage*image=nullptr;if(AImageReader_acquireLatestImage(r,&image)!=AMEDIA_OK||!image)return;int32_t width=0,height=0,row=0,pixel=0;int64_t ts=0;std::uint8_t*data=nullptr;int len=0;AImage_getWidth(image,&width);AImage_getHeight(image,&height);AImage_getTimestamp(image,&ts);AImage_getPlaneRowStride(image,0,&row);AImage_getPlanePixelStride(image,0,&pixel);AImage_getPlaneData(image,0,&data,&len);if(data&&width>0&&height>0&&row>0&&pixel>0){CameraFrame f;f.sequence=++next_sequence_;f.timestamp_ns=ts;f.width=width;f.height=height;f.luma.resize(std::size_t(width)*height);for(int y=0;y<height;y++){const auto*src=data+std::size_t(y)*row;auto*dst=f.luma.data()+std::size_t(y)*width;if(pixel==1)std::memcpy(dst,src,width);else for(int x=0;x<width;x++)dst[x]=src[std::size_t(x)*pixel];}std::scoped_lock lock(mutex_);latest_=std::move(f);}AImage_delete(image);}
bool CameraNdk::consume(CameraFrame&out){std::scoped_lock lock(mutex_);if(!latest_.sequence||latest_.sequence==consumed_sequence_)return false;out=latest_;consumed_sequence_=latest_.sequence;return true;}
}
