#include "engine.hpp"
#include "android_log.hpp"
#include "permissions.hpp"
#include "core/seed.hpp"
#include "core/sha256.hpp"
#include <android/asset_manager.h>
#include <fcntl.h>
#include <time.h>
#include <unistd.h>
#include <algorithm>
#include <cmath>
#include <cstring>
#include <filesystem>
#include <vector>
#ifndef UGTS41_PROFILE_HINT
#define UGTS41_PROFILE_HINT "auto"
#endif
namespace ugts41::android {
namespace {
std::uint32_t percentile(std::vector<std::uint32_t> values,double fraction){if(values.empty())return 0;std::sort(values.begin(),values.end());auto index=std::min<std::size_t>(values.size()-1,std::size_t(std::ceil(fraction*values.size()))-1);return values[index];}
std::uint32_t maximum(const std::vector<std::uint32_t>&values){return values.empty()?0:*std::max_element(values.begin(),values.end());}
}
Engine::Engine(android_app*a):app_(a),demo_(generate_demo_world(0x4b43534545443431ULL,12)){}
Engine::~Engine(){shutdown();}
std::uint64_t Engine::now_ns()const{timespec t{};clock_gettime(CLOCK_BOOTTIME,&t);return std::uint64_t(t.tv_sec)*1'000'000'000ULL+t.tv_nsec;}
std::uint64_t Engine::create_seed()const{std::uint64_t seed=0;int fd=open("/dev/urandom",O_RDONLY|O_CLOEXEC);if(fd>=0){auto n=read(fd,&seed,sizeof(seed));close(fd);if(n==sizeof(seed)&&seed)return seed;}return splitmix64(now_ns()^std::uint64_t(reinterpret_cast<std::uintptr_t>(this)));}
std::vector<std::uint8_t>Engine::asset(const char*path){AAsset*a=AAssetManager_open(app_->activity->assetManager,path,AASSET_MODE_BUFFER);if(!a)return{};auto n=AAsset_getLength(a);std::vector<std::uint8_t>b(n);if(n)AAsset_read(a,b.data(),n);AAsset_close(a);return b;}
bool Engine::initialize_window(){if(!app_->window)return false;if(!renderer_.initialize(app_->window,app_->activity->assetManager))return false;device_=detect_device_info(renderer_.gpu());profile_=select_runtime_profile(device_,UGTS41_PROFILE_HINT);thermal_=thermal_tuning(profile_,0);request_window_frame_rate(app_->window,profile_.presentation_fps);session_seed_=create_seed();extractor_=std::make_unique<SeededFeatureExtractor>(session_seed_,profile_.features);auto p=asset("capture_profile_poco_x7_pro.json");profile_hash_=sha256(p);const char*root=app_->activity->internalDataPath?app_->activity->internalDataPath:"/data/local/tmp";storage_=std::make_unique<SessionStorage>(root);imu_.start(app_->looper,"nl.tomklootwijk.ugtskc.spatial.poco");ensure_camera();UGTS_LOGI("UGTS-KC 4.1 native ready profile=%s seed=%016llx",profile_.id.c_str(),static_cast<unsigned long long>(session_seed_));return true;}
void Engine::terminate_window(){if(recording_)stop_recording();camera_.stop();renderer_.shutdown();}
void Engine::ensure_camera(){if(camera_.active())return;auto now=now_ns();if(now<permission_retry_ns_)return;if(!camera_permission_granted(app_)){if(!camera_requested_){request_camera_permission(app_);camera_requested_=true;}permission_retry_ns_=now+1'000'000'000ULL;return;}camera_requested_=false;if(!camera_.start(profile_.camera_width,profile_.camera_height,profile_.camera_fps))permission_retry_ns_=now+2'000'000'000ULL;}
void Engine::reset_performance_metrics(){processing_us_.clear();capture_age_us_.clear();render_us_.clear();processing_us_.reserve(60'000);capture_age_us_.reserve(60'000);render_us_.reserve(60'000);perf_start_ns_=now_ns();last_camera_sequence_=0;camera_overwritten_=0;render_sample_counter_=0;}
void Engine::log_performance_metrics()const{auto duration_ns=stats_.end_time_ns>perf_start_ns_?stats_.end_time_ns-perf_start_ns_:0;auto fps_x100=duration_ns?std::uint64_t(processing_us_.size())*100'000'000'000ULL/duration_ns:0;UGTS_LOGI("perf duration_ms=%llu processed_frames=%llu effective_fps_x100=%llu camera_overwritten=%llu",static_cast<unsigned long long>(duration_ns/1'000'000ULL),static_cast<unsigned long long>(processing_us_.size()),static_cast<unsigned long long>(fps_x100),static_cast<unsigned long long>(camera_overwritten_));UGTS_LOGI("perf processing_us p50=%u p95=%u p99=%u max=%u samples=%llu",percentile(processing_us_,.50),percentile(processing_us_,.95),percentile(processing_us_,.99),maximum(processing_us_),static_cast<unsigned long long>(processing_us_.size()));UGTS_LOGI("perf capture_age_us p50=%u p95=%u p99=%u max=%u samples=%llu",percentile(capture_age_us_,.50),percentile(capture_age_us_,.95),percentile(capture_age_us_,.99),maximum(capture_age_us_),static_cast<unsigned long long>(capture_age_us_.size()));UGTS_LOGI("perf render_us p50=%u p95=%u p99=%u max=%u samples=%llu",percentile(render_us_,.50),percentile(render_us_,.95),percentile(render_us_,.99),maximum(render_us_),static_cast<unsigned long long>(render_us_.size()));}
void Engine::start_recording(){if(recording_||!storage_)return;session_seed_=create_seed();extractor_=std::make_unique<SeededFeatureExtractor>(session_seed_,profile_.features);selector_.reset();ledger_.reset();stats_={};stats_.session_seed=session_seed_;stats_.start_time_ns=now_ns();KseedHeader h;h.session_seed=session_seed_;h.start_time_ns=stats_.start_time_ns;h.analysis_width=profile_.features.analysis_width;h.analysis_height=profile_.features.analysis_height;h.capture_fps_x100=profile_.camera_fps*100;h.feature_budget=profile_.features.feature_budget;h.storage_mode=profile_.storage_mode;h.profile_hash=profile_hash_;auto cal=camera_.descriptor().calibration;h.calibration_hash=sha256(std::span<const std::uint8_t>(reinterpret_cast<const std::uint8_t*>(cal.data()),cal.size()));if(!storage_->begin(h,profile_.chunk_bytes)){UGTS_LOGE("storage begin: %s",storage_->error().c_str());return;}reset_performance_metrics();recording_=true;EventProposal p;p.proposal_id=stable_id(session_seed_,0x53455353494f4e00ULL,1);p.kind=EventKind::SessionStart;p.timestamp_ns=stats_.start_time_ns;p.stable_id=p.proposal_id;p.spatial_key=session_seed_;p.confidence=1;p.guard=GuardStatus::Confirmed;p.support_ok=p.compatibility_ok=true;commit(p);UGTS_LOGI("recording started");}
void Engine::stop_recording(){if(!recording_)return;EventProposal p;p.proposal_id=stable_id(session_seed_,0x53455353494f4e00ULL,2);p.kind=EventKind::SessionEnd;p.timestamp_ns=now_ns();p.stable_id=p.proposal_id;p.spatial_key=session_seed_;p.confidence=1;p.guard=GuardStatus::Confirmed;p.support_ok=p.compatibility_ok=true;commit(p);stats_.end_time_ns=p.timestamp_ns;stats_.events_committed=ledger_.events().size();stats_.rejected_proposals=ledger_.rejected_count();if(storage_)storage_->finish(stats_,profile_.id,hex_bytes(ledger_.state_hash()));log_performance_metrics();recording_=false;UGTS_LOGI("recording stopped");}
void Engine::commit(const EventProposal&p){++stats_.proposals_seen;VerificationDecision d;if(auto e=ledger_.commit(p,&d)){++stats_.events_committed;if(storage_&&storage_->writer())storage_->writer()->append_event(*e);}else ++stats_.rejected_proposals;}
void Engine::process(const FrameObservation&f,const std::vector<std::uint8_t>&analysis,std::uint64_t raw,bool synthetic){display_luma_=analysis;display_features_=f.features;if(!recording_||thermal_.pause_capture)return;++stats_.frames_seen;stats_.raw_input_bytes+=raw;if(selector_.should_store(f)){++stats_.keyframes_stored;std::span<const std::uint8_t>thumb;if(thermal_.thumbnails)thumb=analysis;if(storage_&&storage_->writer())storage_->writer()->append_frame(f,thumb);ObservationAdapterPolicy policy;policy.feature_proposals_per_keyframe=std::min<std::uint16_t>(24,thermal_.feature_budget/4);for(auto p:proposals_from_frame(f,session_seed_,policy)){if(synthetic)p.tag_mask|=1U<<31U;commit(p);}}}
void Engine::synthetic_frame(std::uint64_t ts){auto w=profile_.features.analysis_width,h=profile_.features.analysis_height;std::vector<std::uint8_t>img(std::size_t(w)*h);for(unsigned y=0;y<h;y++)for(unsigned x=0;x<w;x++){auto n=splitmix64(session_seed_^std::uint64_t((x/8)+(y/8)*32));int v=95+int(45*std::sin((x+frame_index_)*.08))+int(30*std::cos((y-frame_index_/2)*.12))+int(n&31);img[std::size_t(y)*w+x]=std::clamp(v,0,255);}ImuSample imu=imu_.latest();auto e=extractor_->extract(img.data(),w,h,w,1,++frame_index_,ts,imu);process(e.observation,e.analysis_luma,img.size(),true);}
void Engine::update_thermal(){auto n=now_ns();if(n-last_thermal_ns_<1'000'000'000ULL)return;last_thermal_ns_=n;int status=query_thermal_status(app_);if(status!=thermal_.status){thermal_=thermal_tuning(profile_,status);UGTS_LOGI("thermal=%d process_fps=%u features=%u pause=%d",status,thermal_.process_fps,thermal_.feature_budget,thermal_.pause_capture);if(recording_){EventProposal p;p.proposal_id=stable_id(session_seed_,0x544845524d414c00ULL,n/1'000'000'000ULL);p.kind=EventKind::ThermalPolicy;p.timestamp_ns=n;p.stable_id=p.proposal_id;p.spatial_key=status;p.confidence=1;p.guard=GuardStatus::Confirmed;p.support_ok=p.compatibility_ok=true;p.payload={status,thermal_.process_fps,thermal_.feature_budget,thermal_.pause_capture?1:0};commit(p);}}}
void Engine::frame(float dt){time_+=dt;ensure_camera();update_thermal();auto now=now_ns();auto interval=1'000'000'000ULL/std::max<std::uint16_t>(1,thermal_.process_fps);if(now-last_processed_ns_>=interval){CameraFrame c;if(camera_.consume(c)){last_processed_ns_=now;auto processing_start=now_ns();ImuSample imu=imu_.latest();auto e=extractor_->extract(c.luma.data(),c.width,c.height,c.width,1,++frame_index_,c.timestamp_ns,imu);process(e.observation,e.analysis_luma,c.luma.size(),false);auto processing_end=now_ns();if(recording_){processing_us_.push_back(std::uint32_t(std::min<std::uint64_t>((processing_end-processing_start)/1'000ULL,UINT32_MAX)));capture_age_us_.push_back(std::uint32_t(std::min<std::uint64_t>(processing_end>c.timestamp_ns?(processing_end-c.timestamp_ns)/1'000ULL:0,UINT32_MAX)));if(last_camera_sequence_&&c.sequence>last_camera_sequence_+1)camera_overwritten_+=c.sequence-last_camera_sequence_-1;last_camera_sequence_=c.sequence;}}else if(!camera_.active()){last_processed_ns_=now;synthetic_frame(now);}}RenderSnapshot s;s.mode=mode_;s.luma=&display_luma_;s.luma_width=profile_.features.analysis_width;s.luma_height=profile_.features.analysis_height;s.features=&display_features_;s.demo=&demo_;s.stats=&stats_;s.state_hash=ledger_.state_hash();s.seed=session_seed_;s.thermal=thermal_.status;s.recording=recording_;s.camera_active=camera_.active();s.profile=profile_.id;auto render_start=now_ns();renderer_.render(s,time_);if(recording_&&++render_sample_counter_%4==0){auto render_end=now_ns();render_us_.push_back(std::uint32_t(std::min<std::uint64_t>((render_end-render_start)/1'000ULL,UINT32_MAX)));}}
int Engine::handle_input(AInputEvent*e){if(AInputEvent_getType(e)==AINPUT_EVENT_TYPE_KEY){auto action=AKeyEvent_getAction(e),key=AKeyEvent_getKeyCode(e);if(action==AKEY_EVENT_ACTION_UP&&(key==AKEYCODE_VOLUME_UP||key==AKEYCODE_SPACE)){recording_?stop_recording():start_recording();return 1;}}if(AInputEvent_getType(e)!=AINPUT_EVENT_TYPE_MOTION)return 0;auto action=AMotionEvent_getAction(e)&AMOTION_EVENT_ACTION_MASK;float x=AMotionEvent_getX(e,0);if(action==AMOTION_EVENT_ACTION_DOWN){down_x_=x;return 1;}if(action==AMOTION_EVENT_ACTION_UP){float dx=x-down_x_;if(std::abs(dx)>80){int m=(int(mode_)+(dx<0?1:2))%3;mode_=ViewMode(m);}else recording_?stop_recording():start_recording();return 1;}return 1;}
void Engine::shutdown(){if(recording_)stop_recording();camera_.stop();imu_.stop();renderer_.shutdown();}
}
