#include "renderer_bayer.hpp"
#include "android_log.hpp"
#include "core/seed.hpp"
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <cctype>
namespace ugts41::android {
namespace {const std::array<std::array<std::uint8_t,7>,128>&font(){static const auto f=[](){std::array<std::array<std::uint8_t,7>,128> out{};out['A']={14,17,17,31,17,17,17};out['B']={30,17,17,30,17,17,30};out['C']={14,17,16,16,16,17,14};out['D']={30,17,17,17,17,17,30};out['E']={31,16,16,30,16,16,31};out['F']={31,16,16,30,16,16,16};out['G']={14,17,16,23,17,17,14};out['H']={17,17,17,31,17,17,17};out['I']={14,4,4,4,4,4,14};out['J']={7,2,2,2,18,18,12};out['K']={17,18,20,24,20,18,17};out['L']={16,16,16,16,16,16,31};out['M']={17,27,21,21,17,17,17};out['N']={17,25,21,19,17,17,17};out['O']={14,17,17,17,17,17,14};out['P']={30,17,17,30,16,16,16};out['Q']={14,17,17,17,21,18,13};out['R']={30,17,17,30,20,18,17};out['S']={15,16,16,14,1,1,30};out['T']={31,4,4,4,4,4,4};out['U']={17,17,17,17,17,17,14};out['V']={17,17,17,17,17,10,4};out['W']={17,17,17,21,21,21,10};out['X']={17,17,10,4,10,17,17};out['Y']={17,17,10,4,4,4,4};out['Z']={31,1,2,4,8,16,31};out['0']={14,17,19,21,25,17,14};out['1']={4,12,4,4,4,4,14};out['2']={14,17,1,2,4,8,31};out['3']={30,1,1,14,1,1,30};out['4']={2,6,10,18,31,2,2};out['5']={31,16,16,30,1,1,30};out['6']={14,16,16,30,17,17,14};out['7']={31,1,2,4,8,8,8};out['8']={14,17,17,14,17,17,14};out['9']={14,17,17,15,1,1,14};out['-']={0,0,0,31,0,0,0};out['.']={0,0,0,0,0,12,12};out[':']={0,12,12,0,12,12,0};out['/']={1,2,4,8,16,0,0};out[' ']={0,0,0,0,0,0,0};return out;}();return f;}
} // namespace
std::string RendererBayer::asset_text(AAssetManager*m,const char*p){AAsset*a=AAssetManager_open(m,p,AASSET_MODE_BUFFER);if(!a)return{};auto n=AAsset_getLength(a);std::string s(n,'\0');if(n)AAsset_read(a,s.data(),n);AAsset_close(a);return s;}
GLuint RendererBayer::compile(GLenum type,const std::string&s){auto sh=glCreateShader(type);const char*p=s.c_str();glShaderSource(sh,1,&p,nullptr);glCompileShader(sh);GLint ok=0;glGetShaderiv(sh,GL_COMPILE_STATUS,&ok);if(!ok){char log[1024]{};glGetShaderInfoLog(sh,sizeof(log),nullptr,log);UGTS_LOGE("shader: %s",log);glDeleteShader(sh);return 0;}return sh;}
bool RendererBayer::initialize(ANativeWindow*w,AAssetManager*assets){shutdown();display_=eglGetDisplay(EGL_DEFAULT_DISPLAY);if(display_==EGL_NO_DISPLAY||!eglInitialize(display_,nullptr,nullptr))return false;EGLint attrs[]={EGL_RENDERABLE_TYPE,EGL_OPENGL_ES3_BIT,EGL_SURFACE_TYPE,EGL_WINDOW_BIT,EGL_RED_SIZE,8,EGL_GREEN_SIZE,8,EGL_BLUE_SIZE,8,EGL_ALPHA_SIZE,8,EGL_NONE};EGLint count=0;if(!eglChooseConfig(display_,attrs,&config_,1,&count)||count<1)return false;EGLint format=0;eglGetConfigAttrib(display_,config_,EGL_NATIVE_VISUAL_ID,&format);ANativeWindow_setBuffersGeometry(w,0,0,format);EGLint ctx[]={EGL_CONTEXT_CLIENT_VERSION,3,EGL_NONE};context_=eglCreateContext(display_,config_,EGL_NO_CONTEXT,ctx);surface_=eglCreateWindowSurface(display_,config_,w,nullptr);if(context_==EGL_NO_CONTEXT||surface_==EGL_NO_SURFACE||!eglMakeCurrent(display_,surface_,surface_,context_))return false;eglSwapInterval(display_,1);auto vs=compile(GL_VERTEX_SHADER,asset_text(assets,"shaders/present.vert")),fs=compile(GL_FRAGMENT_SHADER,asset_text(assets,"shaders/bayer.frag"));if(!vs||!fs)return false;program_=glCreateProgram();glAttachShader(program_,vs);glAttachShader(program_,fs);glLinkProgram(program_);glDeleteShader(vs);glDeleteShader(fs);GLint linked=0;glGetProgramiv(program_,GL_LINK_STATUS,&linked);if(!linked)return false;u_luma_=glGetUniformLocation(program_,"uLuma");u_mode_=glGetUniformLocation(program_,"uMode");u_pulse_=glGetUniformLocation(program_,"uPulse");glGenTextures(1,&texture_);glBindTexture(GL_TEXTURE_2D,texture_);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_NEAREST);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_NEAREST);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,GL_CLAMP_TO_EDGE);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,GL_CLAMP_TO_EDGE);canvas_.assign(std::size_t(canvas_width_)*canvas_height_,0);const char*r=reinterpret_cast<const char*>(glGetString(GL_RENDERER));gpu_=r?r:"unknown";return true;}
void RendererBayer::pixel(int x,int y,std::uint8_t v){if(x>=0&&y>=0&&x<canvas_width_&&y<canvas_height_)canvas_[std::size_t(y)*canvas_width_+x]=v;}
void RendererBayer::line(int x0,int y0,int x1,int y1,std::uint8_t v){int dx=std::abs(x1-x0),sx=x0<x1?1:-1,dy=-std::abs(y1-y0),sy=y0<y1?1:-1,e=dx+dy;for(;;){pixel(x0,y0,v);if(x0==x1&&y0==y1)break;int e2=2*e;if(e2>=dy){e+=dy;x0+=sx;}if(e2<=dx){e+=dx;y0+=sy;}}}
void RendererBayer::glyph(int x,int y,char c,std::uint8_t v){const auto&g=font()[static_cast<unsigned char>(c)<128?static_cast<unsigned char>(c):static_cast<unsigned char>(' ')];for(int yy=0;yy<7;yy++)for(int xx=0;xx<5;xx++)if(g[yy]&(1<<(4-xx)))pixel(x+xx,y+yy,v);}
void RendererBayer::text(int x,int y,const std::string&s,std::uint8_t v){for(char c:s){glyph(x,y,char(std::toupper(static_cast<unsigned char>(c))),v);x+=6;if(x+5>=canvas_width_)break;}}
void RendererBayer::make_canvas(const RenderSnapshot&s){std::fill(canvas_.begin(),canvas_.end(),5);if(s.mode==ViewMode::Camera&&s.luma&&!s.luma->empty()&&s.luma_width&&s.luma_height){for(int y=0;y<canvas_height_;y++)for(int x=0;x<canvas_width_;x++){auto sx=std::uint32_t(x)*s.luma_width/canvas_width_,sy=std::uint32_t(y)*s.luma_height/canvas_height_;canvas_[std::size_t(y)*canvas_width_+x]=(*s.luma)[std::size_t(sy)*s.luma_width+sx];}if(s.features)for(auto&f:*s.features){int x=int(f.x)*canvas_width_/std::max<int>(1,s.luma_width),y=int(f.y)*canvas_height_/std::max<int>(1,s.luma_height);pixel(x,y,255);pixel(x+1,y,210);}}else if(s.mode==ViewMode::MapDemo&&s.demo){std::fill(canvas_.begin(),canvas_.end(),10);auto mapx=[](float x){return int(std::lround((x+5.0f)*15.0f));};auto mapy=[](float z){return int(std::lround(48.0f-z*12.0f));};for(auto&e:s.demo->edges){auto a=std::find_if(s.demo->nodes.begin(),s.demo->nodes.end(),[&](auto&n){return n.id==e.from;});auto b=std::find_if(s.demo->nodes.begin(),s.demo->nodes.end(),[&](auto&n){return n.id==e.to;});if(a!=s.demo->nodes.end()&&b!=s.demo->nodes.end())line(mapx(a->position.x),mapy(a->position.z),mapx(b->position.x),mapy(b->position.z),e.passable?220:80);}for(auto&n:s.demo->nodes){auto x=mapx(n.position.x),y=mapy(n.position.z);pixel(x,y,255);pixel(x+1,y,255);pixel(x,y+1,255);}}else{for(int y=14;y<76;y++)for(int x=5;x<155;x++){auto i=std::size_t((x+y*151)%32);auto bit=(s.state_hash[i]>>((x+y)&7))&1;pixel(x,y,bit?190:18);}if(s.stats){int bar=std::min<int>(145,s.stats->events_committed/4);for(int x=5;x<5+bar;x++)for(int y=78;y<84;y++)pixel(x,y,235);}}
for(int y=0;y<10;y++)for(int x=0;x<canvas_width_;x++)pixel(x,y,0);text(2,1,s.recording?"REC UGTS 4.1 SEED":"UGTS 4.1 SEED",s.recording?255:210);char line2[64];std::snprintf(line2,sizeof(line2),"%s T%d F%u E%u",s.camera_active?"CAM":"DEMO",s.thermal,s.stats?s.stats->frames_seen:0,s.stats?s.stats->events_committed:0);for(int y=80;y<90;y++)for(int x=0;x<canvas_width_;x++)pixel(x,y,0);text(2,81,line2,220);}
void RendererBayer::render(const RenderSnapshot&s,float time){if(!ready())return;make_canvas(s);eglQuerySurface(display_,surface_,EGL_WIDTH,&window_width_);eglQuerySurface(display_,surface_,EGL_HEIGHT,&window_height_);glViewport(0,0,window_width_,window_height_);glDisable(GL_DEPTH_TEST);glUseProgram(program_);glActiveTexture(GL_TEXTURE0);glBindTexture(GL_TEXTURE_2D,texture_);glTexImage2D(GL_TEXTURE_2D,0,GL_R8,canvas_width_,canvas_height_,0,GL_RED,GL_UNSIGNED_BYTE,canvas_.data());glUniform1i(u_luma_,0);glUniform1i(u_mode_,int(s.mode));glUniform1f(u_pulse_,s.recording?0.5f+0.5f*std::sin(time*8.0f):0.0f);glDrawArrays(GL_TRIANGLES,0,3);eglSwapBuffers(display_,surface_);}
void RendererBayer::shutdown(){if(display_!=EGL_NO_DISPLAY){eglMakeCurrent(display_,EGL_NO_SURFACE,EGL_NO_SURFACE,EGL_NO_CONTEXT);if(texture_)glDeleteTextures(1,&texture_);if(program_)glDeleteProgram(program_);if(context_!=EGL_NO_CONTEXT)eglDestroyContext(display_,context_);if(surface_!=EGL_NO_SURFACE)eglDestroySurface(display_,surface_);eglTerminate(display_);}display_=EGL_NO_DISPLAY;surface_=EGL_NO_SURFACE;context_=EGL_NO_CONTEXT;program_=texture_=0;}
} // namespace ugts41::android
