#include "ledger.hpp"
#include "sha256.hpp"
#include <algorithm>
#include <bit>
namespace ugts41 {namespace {void u32(std::vector<std::uint8_t>&o,std::uint32_t v){for(int i=0;i<4;i++)o.push_back(v>>(i*8));}void u64(std::vector<std::uint8_t>&o,std::uint64_t v){for(int i=0;i<8;i++)o.push_back(v>>(i*8));}void f32(std::vector<std::uint8_t>&o,float v){u32(o,std::bit_cast<std::uint32_t>(v));}}
std::vector<std::uint8_t>encode_proposal_canonical(const EventProposal&p){std::vector<std::uint8_t>o;o.reserve(80);u64(o,p.proposal_id);o.push_back(std::uint8_t(p.kind));u64(o,p.timestamp_ns);u64(o,p.stable_id);u64(o,p.spatial_key);f32(o,p.confidence);f32(o,p.numeric_error);f32(o,p.uncertainty);f32(o,p.relation_value);f32(o,p.metric_a);f32(o,p.metric_b);o.push_back(std::uint8_t(p.guard));std::uint8_t flags=(p.support_ok?1:0)|(p.compatibility_ok?2:0)|(p.metric_required?4:0)|(p.metric_ready?8:0);o.push_back(flags);u32(o,p.tag_mask);for(auto v:p.payload)u32(o,std::uint32_t(v));return o;}
SpatialLedger::SpatialLedger(ProposalVerifier v):verifier_(std::move(v)){reset();}
void SpatialLedger::reset(){events_.clear();nodes_.clear();route_nodes_.clear();route_edges_.clear();rejected_count_=0;static constexpr std::uint8_t init[]={'U','G','T','S','4','1','L','E','D','G','E','R'};state_hash_=sha256(init);}
void SpatialLedger::apply(const EventProposal&p){if(p.kind==EventKind::FeatureRay||p.kind==EventKind::Keyframe||p.kind==EventKind::ManualAnchor||p.kind==EventKind::StateChange){auto&n=nodes_[p.stable_id];if(!n.id){n.id=p.stable_id;n.spatial_key=p.spatial_key;n.confidence=p.confidence;n.uncertainty=p.uncertainty;n.tag_mask=p.tag_mask;n.payload=p.payload;}else{float w=n.evidence_count;n.confidence=(n.confidence*w+p.confidence)/(w+1);n.uncertainty=std::min(n.uncertainty,p.uncertainty);n.tag_mask|=p.tag_mask;n.payload=p.payload;}n.evidence_count++;}else if(p.kind==EventKind::RouteNode){RouteNode n;n.id=p.stable_id;n.position={p.payload[0]/1000.0f,p.payload[1]/1000.0f,p.payload[2]/1000.0f};n.uncertainty=p.uncertainty;n.flags=p.tag_mask;route_nodes_[n.id]=n;}else if(p.kind==EventKind::RouteEdge){RouteEdge e;e.id=p.stable_id;e.from=std::uint64_t(std::uint32_t(p.payload[0]))|(std::uint64_t(std::uint32_t(p.payload[1]))<<32);e.to=std::uint64_t(std::uint32_t(p.payload[2]))|(std::uint64_t(std::uint32_t(p.payload[3]))<<32);e.clearance_lower=p.metric_a;e.slope_upper=p.metric_b;e.confidence=p.confidence;e.passable=(p.tag_mask&1)!=0;route_edges_[e.id]=e;}}
std::optional<LedgerEvent>SpatialLedger::commit(const EventProposal&p,VerificationDecision*out){auto d=verifier_.verify(p);if(out)*out=d;if(!d.accepted){rejected_count_++;return std::nullopt;}LedgerEvent e;e.sequence=events_.size()+1;e.proposal=p;e.pre_hash=state_hash_;apply(p);std::vector<std::uint8_t>b;u32(b,e.sequence);auto pb=encode_proposal_canonical(p);b.insert(b.end(),pb.begin(),pb.end());b.insert(b.end(),e.pre_hash.begin(),e.pre_hash.end());Sha256 s;s.update(state_hash_);s.update(b);e.post_hash=s.finish();state_hash_=e.post_hash;events_.push_back(e);return e;}
}
