#include "pipeline.hpp"
#include "seed.hpp"
#include <algorithm>
#include <cmath>
namespace ugts41 {
std::vector<EventProposal>proposals_from_frame(const FrameObservation&f,std::uint64_t seed,ObservationAdapterPolicy policy){std::vector<EventProposal>o;EventProposal k;k.proposal_id=stable_id(seed,0x4b45594652414d45ULL,f.frame_index);k.kind=EventKind::Keyframe;k.timestamp_ns=f.timestamp_ns;k.stable_id=k.proposal_id;k.spatial_key=f.luma_signature;k.confidence=std::clamp(float(f.features.size())/64.0f,0.0f,1.0f);k.numeric_error=1.0f/std::max<std::uint16_t>(1,f.width);k.uncertainty=1;k.relation_value=float(f.deviation_luma)/255;k.guard=GuardStatus::Confirmed;k.support_ok=k.compatibility_ok=true;k.tag_mask=1;k.payload={std::int32_t(f.frame_index),f.mean_luma,f.deviation_luma,std::int32_t(f.features.size())};o.push_back(k);auto selected=f.features;std::sort(selected.begin(),selected.end(),[](auto&a,auto&b){return a.score>b.score;});if(selected.size()>policy.feature_proposals_per_keyframe)selected.resize(policy.feature_proposals_per_keyframe);for(auto&x:selected){EventProposal p;p.proposal_id=stable_id(seed,0x4652415950524f50ULL,x.ray_key);p.kind=EventKind::FeatureRay;p.timestamp_ns=f.timestamp_ns;p.stable_id=stable_id(seed,0x4645415455524500ULL,x.ray_key);p.spatial_key=x.ray_key;p.confidence=std::clamp(float(x.gradient)/180.0f,0.0f,1.0f);p.numeric_error=std::sqrt(2.0f)/std::max(f.width,f.height);p.uncertainty=policy.relative_uncertainty;p.relation_value=float(x.gradient)/255;p.guard=p.confidence>=policy.confidence_floor?GuardStatus::Confirmed:GuardStatus::Unknown;p.support_ok=p.compatibility_ok=true;p.payload={x.x,x.y,x.intensity,x.gradient};p.tag_mask=2;o.push_back(p);}return o;}
DemoWorld generate_demo_world(std::uint64_t seed,std::uint32_t count){DemoWorld w;count=std::clamp<std::uint32_t>(count,4,64);for(std::uint32_t i=0;i<count;i++){float t=float(i)/float(count-1);RouteNode n;n.id=stable_id(seed,0x524f5554454e4f44ULL,i);n.position={-4+8*t+(seed_unit_float(combine_seed(seed,i*3+1))-.5f)*.55f,0,std::sin(t*6.2831853f)*1.6f+(seed_unit_float(combine_seed(seed,i*3+2))-.5f)*.45f};n.uncertainty=.03f+.04f*seed_unit_float(combine_seed(seed,i*3+3));n.flags=(i==0?1:0)|(i+1==count?2:0);w.nodes.push_back(n);}for(std::uint32_t i=0;i+1<count;i++){RouteEdge e;e.id=stable_id(seed,0x524f555445454447ULL,i);e.from=w.nodes[i].id;e.to=w.nodes[i+1].id;e.clearance_lower=.85f+.65f*seed_unit_float(combine_seed(seed,1000+i));e.slope_upper=.02f+.08f*seed_unit_float(combine_seed(seed,2000+i));e.confidence=.78f+.2f*seed_unit_float(combine_seed(seed,3000+i));e.passable=e.clearance_lower>=.9f&&e.slope_upper<=.09f;w.edges.push_back(e);}return w;}
std::vector<EventProposal>demo_world_proposals(const DemoWorld&w,std::uint64_t seed,std::uint64_t ts,bool metric){std::vector<EventProposal>o;std::uint64_t i=0;for(auto&n:w.nodes){EventProposal p;p.proposal_id=stable_id(seed,0x44454d4f4e4f4445ULL,i++);p.kind=EventKind::RouteNode;p.timestamp_ns=ts+i;p.stable_id=n.id;p.spatial_key=n.id;p.confidence=.98f;p.numeric_error=.005f;p.uncertainty=n.uncertainty;p.guard=GuardStatus::Confirmed;p.support_ok=p.compatibility_ok=true;p.metric_required=true;p.metric_ready=metric;p.tag_mask=n.flags;p.payload={std::int32_t(std::lround(n.position.x*1000)),std::int32_t(std::lround(n.position.y*1000)),std::int32_t(std::lround(n.position.z*1000)),0};o.push_back(p);}for(auto&e:w.edges){EventProposal p;p.proposal_id=stable_id(seed,0x44454d4f45444745ULL,i++);p.kind=EventKind::RouteEdge;p.timestamp_ns=ts+i;p.stable_id=e.id;p.spatial_key=e.id;p.confidence=e.confidence;p.numeric_error=.005f;p.uncertainty=.04f;p.metric_a=e.clearance_lower;p.metric_b=e.slope_upper;p.guard=GuardStatus::Confirmed;p.support_ok=p.compatibility_ok=true;p.metric_required=true;p.metric_ready=metric;p.tag_mask=e.passable?1:0;p.payload={std::int32_t(e.from&0xffffffff),std::int32_t(e.from>>32),std::int32_t(e.to&0xffffffff),std::int32_t(e.to>>32)};o.push_back(p);}return o;}
}
